export type Exchange = {
  code: string;
  name: string;
  region: string;
  suffix: string;
  yahoo: string;
};

export const EXCHANGES: Exchange[] = [
  { code: "NYSE", name: "New York Stock Exchange", region: "Americas", suffix: "", yahoo: "NYQ" },
  { code: "NASDAQ", name: "Nasdaq", region: "Americas", suffix: "", yahoo: "NMS" },
  { code: "AMEX", name: "NYSE American", region: "Americas", suffix: "", yahoo: "ASE" },
  { code: "TSX", name: "Toronto Stock Exchange", region: "Americas", suffix: ".TO", yahoo: "TOR" },
  { code: "TSXV", name: "TSX Venture", region: "Americas", suffix: ".V", yahoo: "VAN" },
  { code: "B3", name: "B3 Brazil", region: "Americas", suffix: ".SA", yahoo: "SAO" },
  { code: "BMV", name: "Bolsa Mexicana", region: "Americas", suffix: ".MX", yahoo: "MEX" },
  { code: "BCS", name: "Santiago", region: "Americas", suffix: ".SN", yahoo: "SGO" },
  { code: "BCBA", name: "Buenos Aires", region: "Americas", suffix: ".BA", yahoo: "BUE" },
  { code: "LSE", name: "London Stock Exchange", region: "Europe", suffix: ".L", yahoo: "LSE" },
  { code: "XETR", name: "Deutsche Börse Xetra", region: "Europe", suffix: ".DE", yahoo: "GER" },
  { code: "FRA", name: "Frankfurt", region: "Europe", suffix: ".F", yahoo: "FRA" },
  { code: "EPA", name: "Euronext Paris", region: "Europe", suffix: ".PA", yahoo: "PAR" },
  { code: "AMS", name: "Euronext Amsterdam", region: "Europe", suffix: ".AS", yahoo: "AMS" },
  { code: "BRU", name: "Euronext Brussels", region: "Europe", suffix: ".BR", yahoo: "BRU" },
  { code: "LIS", name: "Euronext Lisbon", region: "Europe", suffix: ".LS", yahoo: "LIS" },
  { code: "MIL", name: "Borsa Italiana", region: "Europe", suffix: ".MI", yahoo: "MIL" },
  { code: "BME", name: "Bolsa de Madrid", region: "Europe", suffix: ".MC", yahoo: "MCE" },
  { code: "SWX", name: "SIX Swiss Exchange", region: "Europe", suffix: ".SW", yahoo: "EBS" },
  { code: "STO", name: "Nasdaq Stockholm", region: "Europe", suffix: ".ST", yahoo: "STO" },
  { code: "CPH", name: "Nasdaq Copenhagen", region: "Europe", suffix: ".CO", yahoo: "CPH" },
  { code: "OSL", name: "Oslo Børs", region: "Europe", suffix: ".OL", yahoo: "OSL" },
  { code: "HEL", name: "Nasdaq Helsinki", region: "Europe", suffix: ".HE", yahoo: "HEL" },
  { code: "ICE", name: "Nasdaq Iceland", region: "Europe", suffix: ".IC", yahoo: "ICE" },
  { code: "WSE", name: "Warsaw", region: "Europe", suffix: ".WA", yahoo: "WSE" },
  { code: "PRA", name: "Prague", region: "Europe", suffix: ".PR", yahoo: "PRA" },
  { code: "VIE", name: "Vienna", region: "Europe", suffix: ".VI", yahoo: "VIE" },
  { code: "ATH", name: "Athens", region: "Europe", suffix: ".AT", yahoo: "ATH" },
  { code: "IST", name: "Borsa Istanbul", region: "Europe", suffix: ".IS", yahoo: "IST" },
  { code: "ISE", name: "Euronext Dublin", region: "Europe", suffix: ".IR", yahoo: "ISE" },
  { code: "TSE", name: "Tokyo Stock Exchange", region: "Asia-Pacific", suffix: ".T", yahoo: "JPX" },
  { code: "HKEX", name: "Hong Kong Exchange", region: "Asia-Pacific", suffix: ".HK", yahoo: "HKG" },
  { code: "SSE", name: "Shanghai", region: "Asia-Pacific", suffix: ".SS", yahoo: "SHH" },
  { code: "SZSE", name: "Shenzhen", region: "Asia-Pacific", suffix: ".SZ", yahoo: "SHZ" },
  { code: "KRX", name: "Korea Exchange", region: "Asia-Pacific", suffix: ".KS", yahoo: "KSC" },
  { code: "KOSDAQ", name: "KOSDAQ", region: "Asia-Pacific", suffix: ".KQ", yahoo: "KOE" },
  { code: "TWSE", name: "Taiwan Stock Exchange", region: "Asia-Pacific", suffix: ".TW", yahoo: "TAI" },
  { code: "SGX", name: "Singapore Exchange", region: "Asia-Pacific", suffix: ".SI", yahoo: "SES" },
  { code: "ASX", name: "Australian Securities Exchange", region: "Asia-Pacific", suffix: ".AX", yahoo: "ASX" },
  { code: "NZX", name: "New Zealand Exchange", region: "Asia-Pacific", suffix: ".NZ", yahoo: "NZE" },
  { code: "NSE", name: "National Stock Exchange of India", region: "Asia-Pacific", suffix: ".NS", yahoo: "NSI" },
  { code: "BSE", name: "BSE India", region: "Asia-Pacific", suffix: ".BO", yahoo: "BSE" },
  { code: "IDX", name: "Indonesia Stock Exchange", region: "Asia-Pacific", suffix: ".JK", yahoo: "JKT" },
  { code: "SET", name: "Stock Exchange of Thailand", region: "Asia-Pacific", suffix: ".BK", yahoo: "SET" },
  { code: "KLSE", name: "Bursa Malaysia", region: "Asia-Pacific", suffix: ".KL", yahoo: "KLS" },
  { code: "PSE", name: "Philippine Stock Exchange", region: "Asia-Pacific", suffix: ".PS", yahoo: "PHS" },
  { code: "HOSE", name: "Ho Chi Minh", region: "Asia-Pacific", suffix: ".VN", yahoo: "VNM" },
  { code: "TASE", name: "Tel Aviv", region: "Middle East & Africa", suffix: ".TA", yahoo: "TLV" },
  { code: "TADAWUL", name: "Saudi Exchange", region: "Middle East & Africa", suffix: ".SR", yahoo: "SAU" },
  { code: "QSE", name: "Qatar Stock Exchange", region: "Middle East & Africa", suffix: ".QA", yahoo: "DOH" },
  { code: "DFM", name: "Dubai Financial Market", region: "Middle East & Africa", suffix: ".AE", yahoo: "DIF" },
  { code: "ADX", name: "Abu Dhabi Securities", region: "Middle East & Africa", suffix: ".AD", yahoo: "ADI" },
  { code: "EGX", name: "Egyptian Exchange", region: "Middle East & Africa", suffix: ".CA", yahoo: "CAI" },
  { code: "JSE", name: "Johannesburg Stock Exchange", region: "Middle East & Africa", suffix: ".JO", yahoo: "JNB" },
  { code: "NGX", name: "Nigerian Exchange", region: "Middle East & Africa", suffix: ".NG", yahoo: "LAG" },
  { code: "KSE", name: "Kuwait Stock Exchange", region: "Middle East & Africa", suffix: ".KW", yahoo: "KUW" },
];

export const REGIONS = [
  "Americas",
  "Europe",
  "Asia-Pacific",
  "Middle East & Africa",
] as const;

export const UNIVERSES: Record<string, { label: string; symbols: string[] }> = {
  us: {
    label: "US mega-cap",
    symbols: [
      "AAPL",
      "MSFT",
      "NVDA",
      "GOOGL",
      "AMZN",
      "META",
      "TSLA",
      "BRK-B",
      "JPM",
      "UNH",
      "V",
      "XOM",
      "JNJ",
      "WMT",
      "MA",
      "PG",
      "AVGO",
      "ORCL",
      "HD",
      "COST",
    ],
  },
  indices: {
    label: "World indices",
    symbols: [
      "^GSPC",
      "^DJI",
      "^IXIC",
      "^RUT",
      "^FTSE",
      "^GDAXI",
      "^FCHI",
      "^STOXX50E",
      "^N225",
      "^HSI",
      "000001.SS",
      "^AXJO",
      "^BSESN",
      "^KS11",
      "^GSPTSE",
      "^BVSP",
      "^MXX",
      "^TA125.TA",
      "^JN0U.JO",
      "^NZ50",
    ],
  },
  europe: {
    label: "Europe",
    symbols: [
      "SAP.DE",
      "ASML.AS",
      "NESN.SW",
      "MC.PA",
      "OR.PA",
      "SIE.DE",
      "AIR.PA",
      "SHEL.L",
      "AZN.L",
      "HSBA.L",
      "NOVN.SW",
      "ROG.SW",
      "ITX.MC",
      "ENEL.MI",
      "UNA.AS",
    ],
  },
  asia: {
    label: "Asia-Pacific",
    symbols: [
      "7203.T",
      "6758.T",
      "9984.T",
      "0700.HK",
      "9988.HK",
      "3690.HK",
      "005930.KS",
      "000660.KS",
      "RELIANCE.NS",
      "TCS.NS",
      "INFY.NS",
      "BHP.AX",
      "CBA.AX",
      "2330.TW",
      "D05.SI",
    ],
  },
  crypto: {
    label: "Crypto",
    symbols: [
      "BTC-USD",
      "ETH-USD",
      "SOL-USD",
      "XRP-USD",
      "DOGE-USD",
      "ADA-USD",
      "AVAX-USD",
      "LINK-USD",
      "DOT-USD",
      "BNB-USD",
    ],
  },
  forex: {
    label: "FX majors",
    symbols: [
      "EURUSD=X",
      "GBPUSD=X",
      "USDJPY=X",
      "AUDUSD=X",
      "USDCAD=X",
      "USDCHF=X",
      "NZDUSD=X",
      "EURGBP=X",
      "USDCNY=X",
      "USDINR=X",
    ],
  },
  commodities: {
    label: "Commodities",
    symbols: ["GC=F", "SI=F", "CL=F", "NG=F", "HG=F", "ZC=F", "ZS=F", "ZW=F", "PL=F", "PA=F"],
  },
};

export const DEFAULT_WATCHLISTS = [
  {
    id: "core",
    name: "Core",
    symbols: ["AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "META", "TSLA", "JPM", "AVGO", "BRK-B"],
  },
  {
    id: "indices",
    name: "Indices",
    symbols: ["^GSPC", "^DJI", "^IXIC", "^FTSE", "^GDAXI", "^N225", "^HSI", "^AXJO", "^BSESN"],
  },
  {
    id: "crypto",
    name: "Crypto",
    symbols: ["BTC-USD", "ETH-USD", "SOL-USD", "XRP-USD", "DOGE-USD"],
  },
  {
    id: "fx",
    name: "Forex",
    symbols: ["EURUSD=X", "GBPUSD=X", "USDJPY=X", "AUDUSD=X", "USDCNY=X"],
  },
  {
    id: "global",
    name: "Global",
    symbols: [
      "7203.T",
      "0700.HK",
      "RELIANCE.NS",
      "SAP.DE",
      "NESN.SW",
      "BHP.AX",
      "005930.KS",
      "SHEL.L",
      "RY.TO",
      "MC.PA",
    ],
  },
];

export const MARKET_HEATMAP = [
  { symbol: "^GSPC", label: "S&P 500" },
  { symbol: "^DJI", label: "Dow" },
  { symbol: "^IXIC", label: "Nasdaq" },
  { symbol: "^RUT", label: "Russell" },
  { symbol: "^GSPTSE", label: "TSX" },
  { symbol: "^BVSP", label: "Bovespa" },
  { symbol: "^MXX", label: "IPC Mex" },
  { symbol: "^FTSE", label: "FTSE 100" },
  { symbol: "^GDAXI", label: "DAX" },
  { symbol: "^FCHI", label: "CAC 40" },
  { symbol: "^STOXX50E", label: "Euro Stoxx" },
  { symbol: "^N225", label: "Nikkei" },
  { symbol: "^HSI", label: "Hang Seng" },
  { symbol: "000001.SS", label: "Shanghai" },
  { symbol: "^AXJO", label: "ASX 200" },
  { symbol: "^BSESN", label: "Sensex" },
  { symbol: "^KS11", label: "KOSPI" },
  { symbol: "^TWII", label: "Taiwan" },
  { symbol: "^STI", label: "Straits" },
  { symbol: "^JN0U.JO", label: "JSE Top 40" },
  { symbol: "BTC-USD", label: "Bitcoin" },
  { symbol: "ETH-USD", label: "Ether" },
  { symbol: "EURUSD=X", label: "EUR/USD" },
  { symbol: "GC=F", label: "Gold" },
];
